import sys
import os
import re
from datetime import date, datetime, timezone

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "."))

from app.core.database import engine, SessionLocal, Base
from app.models.models import Policy, Category, Source, PolicyTimeline, PolicyCategory, User
from app.core.security import get_password_hash


POLICIES_DATA = [
    {
        "title": "Penyesuaian Tarif Pajak Penghasilan (PPh) Pasal 17 Tahun 2025",
        "status": "berlaku",
        "slug": "penyesuaian-tarif-pph-17-tahun-2025",
        "category_slug": "pajak",
        "summary_30sec": "Pemerintah menyesuaikan tarif PPh Pasal 17 berdasarkan UU HPP. Tarif progresif untuk wajib pajak orang pribadi menjadi 5 lapis (5%-35%), dan badan menjadi 20% flat. Berlaku efektif sejak 2025.",
        "summary_long": "Undang-Undang Harmonisasi Peraturan Perpajakan (UU HPP) mengubah struktur tarif PPh Pasal 17 dari 4 lapis menjadi 5 lapis untuk orang pribadi (5%, 15%, 25%, 30%, 35%) dan tarif flat 20% untuk badan. Perubahan ini menyasar penghasilan tahunan di atas Rp5 miliar yang dikenakan tarif tertinggi 35%. Pemerintah mengklaim reformasi ini memperluas basis pajak dan menciptakan keadilan fiskal.",
        "simple_explanation": "Apa sih yang berubah? Tarif pajak penghasilan kamu sekarang pakai sistem baru. Kalau gaji kamu di bawah Rp60 juta setahun, tarifnya masih 5%. Tapi buat yang penghasilannya di atas Rp5 miliar setahun, tarifnya naik jadi 35%. Kenapa diubah? Pemerintah bilang pajak yang kaya harus bayar lebih besar supaya adil. Duitnya mau dipakai buat apa? Kata mereka masuk ke APBN untuk layanan publik. Dampaknya gimana? Buat karyawan dengan gaji menengah ke bawah, nggak banyak berubah. Tapi buat pengusaha dan eksekutif top, pajaknya bisa lebih besar.",
        "impact_explanation": "Siapa yang terdampak: Wajib pajak orang pribadi dengan penghasilan di atas Rp5 miliar per tahun, badan usaha yang sebelumnya bayar tarif 22-25% kini 20% flat.\nApa yang berubah: Tarif tertinggi untuk OP naik dari 30% jadi 35%, tarif badan turun jadi 20% flat.\nKapan berlaku: Efektif tahun pajak 2025.",
        "affected_groups": "Wajib pajak orang pribadi berpenghasilan tinggi, perusahaan, pegawai dengan gaji之士2Rp5 miliar/tahun",
        "government_claim": "Reformasi ini memperluas basis pajak, meningkatkan keadilan fiskal, dan menyederhanakan tarif pajak badan.",
        "public_criticism": "Kritik menyebut tarif 35% bisa mendorong penghindaran pajak dan kaburnya modal ke luar negeri. Beberapa pengusaha mempertanyakan daya saing Indonesia setelah kenaikan tarif.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 1, 2, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2021, 10, 7), "title": "UU HPP disahkan DPR", "description": "Undang-Undang Harmonisasi Peraturan Perpajakan disahkan menjadi undang-undang."},
            {"date": date(2025, 1, 1), "title": "Tarif baru berlaku efektif", "description": "Tarif PPh 5 lapis dan tarif badan 20% mulai berlaku untuk tahun pajak 2025."},
        ],
        "sources": [
            {"source_type": "official", "title": "UU Nomor 7 Tahun 2021 tentang Harmonisasi Peraturan Perpajakan", "url": "https://jdih.setneg.go.id/", "snippet": "Undang-Undang Harmonisasi Peraturan Perpajakan yang mengatur perubahan tarif PPh.", "site_name": "JDIH Setneg", "published_date": date(2021, 10, 7), "verification_status": "verified"},
            {"source_type": "news", "title": "Tarif PPh 2025 Berlaku Mulai Januari, Ini Rinciannya", "url": "https://finance.detik.com/", "snippet": "Penjelasan lengkap tarif PPh baru yang berlaku mulai 2025.", "site_name": "DetikFinance", "published_date": date(2024, 12, 28), "verification_status": "needs_verification"},
        ],
    },
    {
        "title": "Program Kartu Prakerja Gelombang 2025",
        "status": "berlaku",
        "slug": "program-kartu-prakerja-gelombang-2025",
        "category_slug": "tenaga-kerja",
        "summary_30sec": "Prakerja kembali dibuka untuk gelombang 2025. Peserta mendapat insentif hingga Rp3,5 juta untuk pelatihan digital dan vokasi. Program ini menyasar pekerja yang terkena PHK dan pencari kerja.",
        "summary_long": "Program Kartu Prakerja dilanjutkan pada 2025 dengan beberapa perubahan. Insentif tetap Rp3,5 juta per peserta, namun pilihan pelatihan lebih fokus ke digital skills dan vokasi. Pemerintah mengalokasikan anggaran sekitar Rp3,7 triliun. Kritik tetap ada terkait efektivitas program dalam menciptakan lapangan kerja permanen.",
        "simple_explanation": "Apa si Prakerja? Ini program pemerintah yang kasih bantuan biaya pelatihan buat kamu yang lagi cari kerja atau kena PHK. Kamu dapet saldo Rp3,5 juta yang bisa dipakai buat ikut kursus online. Kenapa ada program ini? Karena banyak yang kehilangan kerjaan dan butuh skill baru biar bisa kerja lagi. Dampaknya gimana? Buat yang ikut, bisa dapet skill baru dan sertifikat. Tapi kritik bilang program ini belum tentu bikin lulusannya langsung dapet kerja.",
        "impact_explanation": "Siapa yang terdampak: Pekerja yang terkena PHK, pencari kerja baru, pekerja informal\nApa yang berubah: Peserta dapat saldo Rp3,5 juta untuk pelatihan digital/vokasi\nKapan berlaku: Pendaftaran dibuka sepanjang 2025",
        "affected_groups": "Pekerra PHK, pencari kerja, pekerja informal",
        "government_claim": "Prakerja membantu jutaan pekerja mendapatkan skill baru dan meningkatkan daya saing di pasar tenaga kerja digital.",
        "public_criticism": "Kritik menyebut Prakerja tidak efektif menciptakan lapangan kerja permanen. Banyak lulusan yang tetap menganggur setelah pelatihan.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 2, 15, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2020, 4, 1), "title": "Prakerja pertama kali diluncurkan", "description": "Program dimulai sebagai respon terhadap dampak pandemi COVID-19."},
            {"date": date(2025, 1, 10), "title": "Gelombang 2025 dibuka", "description": "Pendaftaran gelombang baru dibuka dengan fokus digital skills."},
        ],
        "sources": [
            {"source_type": "official", "title": "Prakerja Gelombang 2025 Resmi Dibuka", "url": "https://www.prakerja.go.id/", "snippet": "Informasi resmi pendaftaran Prakerja gelombang 2025.", "site_name": "Prakerja.go.id", "published_date": date(2025, 1, 10), "verification_status": "verified"},
            {"source_type": "news", "title": "Prakerja 2025 Dibuka, Ini yang Berubah", "url": "https://www.kompas.com/", "snippet": "Perubahan dan kelanjutan program Prakerja di tahun 2025.", "site_name": "Kompas", "published_date": date(2025, 1, 12), "verification_status": "needs_verification"},
        ],
    },
    {
        "title": "Kenaikan Upah Minimum Provinsi (UMP) 2025",
        "status": "berlaku",
        "slug": "kenaikan-ump-2025",
        "category_slug": "tenaga-kerja",
        "summary_30sec": "Pemerintah menetapkan kenaikan UMP rata-rata 6,5% untuk 2025. DKI Jakarta memiliki UMP tertinggi sebesar Rp5.396.760. Kenaikan ditetapkan melalui PP 51/2024.",
        "summary_long": "Melalui Peraturan Pemerintah Nomor 51 Tahun 2024, pemerintah menetapkan formula baru perhitungan UMP yang mempertimbangkan inflasi, pertumbuhan ekonomi, dan indeks paritas daya beli. Rata-rata kenaikan UMP 2025 sekitar 6,5%. DKI Jakarta memiliki UMP tertinggi di Rp5.396.760, sementara provinsi dengan UMP terendah ada di sekitar Rp2.8 juta.",
        "simple_explanation": "Apa yang berubah? Gaji minimum di tiap provinsi naik rata-rata 6,5% mulai Januari 2025. Di Jakarta, UMP-nya jadi sekitar Rp5,4 juta per bulan. Kenapa naik? Pemerintah hitung berdasarkan inflasi dan kebutuhan hidup layak. Ada rumus baru yang katanya lebih adil. Dampaknya gimana? Buat pekerja yang gajinya di bawah UMP, berarti gaji naik. Tapi pengusaha kecil bisa kesulitan karena biaya tenaga kerja naik.",
        "impact_explanation": "Siapa yang terdampak: Seluruh pekerja yang gajinya di bawah UMP baru, UMKM dan pengusaha kecil\nApa yang berubah: UMP naik rata-rata 6,5%, rumus perhitungan baru\nKapan berlaku: 1 Januari 2025",
        "affected_groups": "Pekerja bergaji minimum, UMKM, pengusaha",
        "government_claim": "Formula baru lebih adil karena mempertimbangkan daya beli dan kebutuhan hidup layak.",
        "public_criticism": "Serikat buruh menilai kenaikan belum mencukupi kebutuhan hidup layak. Pengusaha kecil merasa beban biaya tenaga kerja semakin berat.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 1, 5, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2024, 11, 15), "title": "PP 51/2024 ditetapkan", "description": "Peraturan Pemerintah tentang perhitungan UMP baru ditetapkan."},
            {"date": date(2025, 1, 1), "title": "UMP baru berlaku", "description": "UMP 2025 berlaku di seluruh provinsi."},
        ],
        "sources": [
            {"source_type": "official", "title": "PP Nomor 51 Tahun 2024 tentang Upah Minimum", "url": "https://jdih.kemnaker.go.id/", "snippet": "Peraturan Pemerintah tentang penetapan upah minimum 2025.", "site_name": "JDIH Kemnaker", "published_date": date(2024, 11, 15), "verification_status": "verified"},
            {"source_type": "news", "title": "UMP 2025 Naik Rata-Rata 6,5%, Ini Daftarnya", "url": "https://www.cnbindonesia.com/", "snippet": "Daftar lengkap UMP seluruh provinsi untuk tahun 2025.", "site_name": "CNN Indonesia", "published_date": date(2024, 11, 30), "verification_status": "needs_verification"},
        ],
    },
    {
        "title": "Kredit Usaha Rakyat (KUR) Bunga Rendah 2025",
        "status": "berlaku",
        "slug": "kur-bunga-rendah-2025",
        "category_slug": "umkm",
        "summary_30sec": "Pemerintah memperpanjang suku bunga KUR 3% hingga 2025 untuk sektor tertentu. Plafon KUR mikro naik menjadi Rp50 juta. Program ini menyasar UMKM yang sulit mengakses permodalan.",
        "summary_long": "Program KUR dengan suku bunga 3% diperpanjang untuk 2025, khususnya untuk sektor produktif. Plafon KUR mikro dinaikkan dari Rp25 juta menjadi Rp50 juta. Total alokasi KUR 2025 ditetapkan sebesar Rp320 triliun. Pemerintah memberikan subsididi bunga 3,5% sehingga bunga efektif yang dibayar debitur hanya 3% per tahun.",
        "simple_explanation": "Apa itu KUR bunga rendah? Ini program pemerintah yang bikin UMKM bisa minjam uang dari bank dengan bunga cuma 3% per tahun. Jauh lebih murah dari pinjaman biasa yang bisa 10-20%. Kenapa dibuat? Karena banyak UMKM susah dapet modal dari bank. Dengan bunga rendah, harapannya UMKM bisa berkembang. Dampaknya gimana? Buat UMKM, ini kesempatan bagus buat ngembangin usaha dengan biaya murah. Tapi prosesnya kadang ribet dan nggak semua bank aktif salurkan.",
        "impact_explanation": "Siapa yang terdampak: UMKM, pelaku usaha mikro dan kecil\nApa yang berubah: Plafon KUR mikro naik jadi Rp50 juta, bunga 3% diperpanjang\nKapan berlaku: Sepanjang 2025",
        "affected_groups": "UMKM, pelaku usaha mikro dan kecil",
        "government_claim": "KUR bunga 3% membantu UMKM mengakses permodalan dengan biaya terjangkau untuk mengembangkan usaha.",
        "public_criticism": "Beberapa UMKM mengeluhkan proses pengajuan yang rumit dan bank yang kurang proaktif menyalurkan KUR.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 1, 20, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2024, 12, 1), "title": "Pengumuman perpanjangan KUR bunga 3%", "description": "Pemerintah mengumumkan perpanjangan program KUR suku bunga 3%."},
            {"date": date(2025, 1, 1), "title": "KUR bunga 3% berlaku", "description": "Program KUR dengan bunga efektif 3% mulai berlaku untuk 2025."},
        ],
        "sources": [
            {"source_type": "official", "title": "Perpres KUR 2025: Bunga 3% Diperpanjang", "url": "https://kUR.go.id/", "snippet": "Informasi resmi program KUR bunga rendah.", "site_name": "KUR.go.id", "published_date": date(2024, 12, 1), "verification_status": "verified"},
            {"source_type": "news", "title": "KUR 2025: Plafon Naik, Bunga Tetap 3 Persen", "url": "https://bisnis.tempo.co/", "snippet": "Detail perubahan KUR untuk tahun 2025.", "site_name": "Tempo Bisnis", "published_date": date(2024, 12, 5), "verification_status": "needs_verification"},
        ],
    },
    {
        "title": "Program Indonesia Pintar (PIP) Fase III",
        "status": "berlaku",
        "slug": "program-indonesia-pintar-pip-fase-iii",
        "category_slug": "pendidikan",
        "summary_30sec": "PIP fase III menyediakan bantuan pendidikan Rp900.000-1.800.000 per tahun untuk siswa miskin dan rentan. Program ini diperluas ke jenjang SMA/SMK dan sederajat.",
        "summary_long": "Program Indonesia Pintar (PIP) fase III diluncurkan dengan peningkatan besaran bantuan. Siswa SD mendapat Rp900.000/tahun, SMP Rp1.100.000/tahun, SMA/SMK Rp1.800.000/tahun. Program menyasar siswa dari keluarga miskin, rentan, dan penyandang disabilitas. Pemerintah mengalokasikan anggaran sekitar Rp12,4 triliun untuk 2025.",
        "simple_explanation": "Apa itu PIP? Program Indonesia Pintar kasih bantuan uang buat siswa yang keluarganya kurang mampu, biar mereka tetap bisa sekolah. Berapa yang dikasih? SD: Rp900rb/tahun, SMP: Rp1,1juta/tahun, SMA/SMK: Rp1,8juta/tahun. Buat siapa? Siswa dari keluarga miskin, keluarga rentan, dan penyandang disabilitas.",
        "impact_explanation": "Siapa yang terdampak: Siswa dari keluarga miskin dan rentan, penyandang disabilitas\nApa yang berubah: Besaran bantuan naik, cakupan diperluas\nKapan berlaku: Tahun ajaran 2025/2026",
        "affected_groups": "Siswa miskin dan rentan, penyandang disabilitas",
        "government_claim": "PIP memastikan tidak ada siswa yang putus sekolah karena masalah ekonomi.",
        "public_criticism": "Masih ada siswa yang berhak namun tidak terdata dan tidak menerima bantuan.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 1, 10, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2024, 8, 1), "title": "PIP fase III diumumkan", "description": "Kemendikbudristek mengumumkan PIP fase III dengan besaran baru."},
            {"date": date(2025, 1, 1), "title": "PIP fase III berlaku", "description": "Bantuan PIP mulai disalurkan untuk tahun ajaran baru."},
        ],
        "sources": [
            {"source_type": "official", "title": "PIP Fase III: Besaran Bantuan dan Syarat Pendaftaran", "url": "https://pip.kemendikbud.go.id/", "snippet": "Informasi resmi program Indonesia Pintar.", "site_name": "Kemendikbud", "published_date": date(2024, 8, 1), "verification_status": "verified"},
            {"source_type": "news", "title": "Bantuan PIP 2025 Naik, Cek Besarannya", "url": "https://edukasi.kompas.com/", "snippet": "Detail besaran bantuan PIP untuk 2025.", "site_name": "Kompas Edukasi", "published_date": date(2024, 12, 20), "verification_status": "needs_verification"},
        ],
    },
    {
        "title": "Penyesuaian Iuran BPJS Kesehatan Kelas 3",
        "status": "dibahas",
        "slug": "penyesuaian-iuran-bpjs-kesehatan-kelas-3",
        "category_slug": "kesehatan",
        "summary_30sec": "Pemerintah membahas kenaikan iuran BPJS Kesehatan kelas 3 dari Rp42.000 menjadi Rp51.000 per bulan. Kenaikan ini untuk menyesuaikan dengan inflasi biaya kesehatan.",
        "summary_long": "Kementerian Kesehatan dan BPJS Kesehatan mengajukan rencana kenaikan iuran kelas 3 sebesar sekitar 21%, dari Rp42.000 menjadi Rp51.000 per bulan per orang. Alasan utama adalah deficit yang terus membesar dan kenaikan biaya layanan kesehatan. Diskusi masih berlangsung di DPR dan belum ada keputusan final.",
        "simple_explanation": "Apa yang mau diubah? Iuran BPJS Kesehatan buat kelas 3 mau dinaikin dari Rp42.000 jadi Rp51.000 per bulan per orang. Kenapa naik? BPJS katanya defisit dan biaya kesehatan makin mahal. Dampaknya gimana? Buat yang pakai kelas 3, iuran bulanan naik Rp9.000. Belum final sih, masih dibahas di DPR.",
        "impact_explanation": "Siapa yang terdampak: Peserta BPJS Kesehatan kelas 3 (sekitar 80 juta jiwa)\nApa yang berubah: Iuran naik dari Rp42.000 jadi Rp51.000/bulan\nKapan berlaku: Masih dibahas, target 2025",
        "affected_groups": "Peserta BPJS kelas 3, pekerja informal, masyarakat miskin",
        "government_claim": "Kenaikan iuran diperlukan untuk keberlanjutan program JKN dan menutup defisit BPJS.",
        "public_criticism": "Masyarakat menilai kenaikan iuran tidak sebanding dengan kualitas layanan yang masih bermasalah. Antrean panjang dan rujukan ditolak masih sering terjadi.",
        "source_confidence": "medium",
        "verification_status": "needs_verification",
        "published_status": "draft",
    },
    {
        "title": "Penghapusan PPnBM Mobil Listrik",
        "status": "disahkan",
        "slug": "penghapusan-ppnbm-mobil-listrik",
        "category_slug": "pajak",
        "summary_30sec": "Pemerintah menghapus PPnBM untuk kendaraan bermotor listrik (KBL) bersistem baterai melalui PP 58/2024. Kebijakan ini bertujuan mendorong adopsi kendaraan listrik di Indonesia.",
        "summary_long": "Melalui Peraturan Pemerintah Nomor 58 Tahun 2024, pemerintah menghapus pembebanan PPnBM untuk KBL bersistem baterai yang diproduksi secara lokal. Kebijakan ini bagian dari strategi Perpres 55/2019 tentang Percepatan Program Kendaraan Bermotor Listrik. Motor listrik juga mendapatkan fasilitas bebas PPnBM.",
        "simple_explanation": "Apa yang diubah? Mobil dan motor listrik yang diproduksi di Indonesia sekarang bebas PPnBM (pajak penjualan barang mewah). Artinya harganya bisa lebih murah. Kenapa? Pemerintah mau orang Indonesia pakai kendaraan listrik supaya polusi berkurang. Dampaknya gimana? Buat konsumen, harga EV lokal bisa turun. Tapi mobil listrik impor tetap kena pajak tinggi.",
        "impact_explanation": "Siapa yang terdampak: Konsumen kendaraan listrik, produsen EV lokal, industri otomotif\nApa yang berubah: PPnBM 0% untuk KBL bersistem baterai lokal\nKapan berlaku: Efektif sejak PP 58/2024 ditetapkan",
        "affected_groups": "Konsumen EV, produsen otomotif lokal, industri baterai",
        "government_claim": "Penghapusan PPnBM mendorong investasi industri EV lokal dan mengurangi emisi karbon.",
        "public_criticism": "Kebijakan dinilai lebih menguntungkan produsen asing yang merakit di Indonesia. Infrastruktur pengisian daya masih minim.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2024, 12, 1, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2019, 8, 8), "title": "Perpres 55/2019 tentang Percepatan KBL", "description": "Presiden menandatangani Perpres percepatan program kendaraan bermotor listrik."},
            {"date": date(2024, 10, 1), "title": "PP 58/2024 ditetapkan", "description": "Penghapusan PPnBM untuk KBL bersistem baterai."},
        ],
        "sources": [
            {"source_type": "official", "title": "PP No. 58 Tahun 2024 tentang Penghapusan PPnBM KBL", "url": "https://jdih.setneg.go.id/", "snippet": "Peraturan Pemerintah tentang penghapusan PPnBM KBL.", "site_name": "JDIH Setneg", "published_date": date(2024, 10, 1), "verification_status": "verified"},
            {"source_type": "news", "title": "PPnBM Mobil Listrik Dihapus, Ini Dampaknya", "url": "https://otomotif.kompas.com/", "snippet": "Analisis dampak penghapusan PPnBM bagi konsumen.", "site_name": "Kompas Otomotif", "published_date": date(2024, 10, 3), "verification_status": "needs_verification"},
        ],
    },
    {
        "title": "Peraturan PSE dan Pelindungan Data Pribadi",
        "status": "berlaku",
        "slug": "peraturan-pse-pelindungan-data-pribadi",
        "category_slug": "digital-teknologi",
        "summary_30sec": "UU PDP resmi berlaku sejak Oktober 2024. Perusahaan wajib melindungi data pribadi pengguna. Pelanggaran dikenai denda hingga 2% pendapatan tahunan. PSE juga diwajibkan mendaftar ke Kominfo.",
        "summary_long": "Undang-Undang Nomor 27 Tahun 2022 tentang Pelindungan Data Pribadi (UU PDP) mulai berlaku penuh pada 17 Oktober 2024. Regulasi ini mewajibkan seluruh Penyelenggara Sistem Elektronik (PSE) mendaftar ke Kominfo, mengamanahkan data pengguna, dan memberikan hak-hak subjek data. Pelanggaran dapat dikenai sanksi pidana dan denda administratif hingga 2% pendapatan tahunan.",
        "simple_explanation": "Apa yang baru? Sekarang ada undang-undang yang wajibin perusahaan pelindungin data pribadi kamu. Kalau data kamu bocor, perusahaan bisa kena denda besar. Apa hak kamu? Kamu bisa minta perusahaan hapus data kamu, minta tahu data apa aja yang mereka simpan, dan protes kalau data dipakai tanpa izin. Dampaknya gimana? Perusahaan harus ubah cara mereka simpan data. Ada masa transisi 2 tahun buat nyiapin semuanya.",
        "impact_explanation": "Siapa yang terdampak: Seluruh perusahaan yang mengelola data pribadi, masyarakat pengguna layanan digital\nApa yang berubah: Kewajiban perlindungan data, hak subjek data, sanksi pelanggaran\nKapan berlaku: 17 Oktober 2024 (masa transisi 2 tahun)",
        "affected_groups": "Perusahaan teknologi, PSE, masyarakat pengguna layanan digital",
        "government_claim": "UU PDP memberikan perlindungan hukum bagi data pribadi masyarakat dan meningkatkan kepercayaan ekonomi digital.",
        "public_criticism": "Belum ada lembaga pengawas PDP yang independen. Masa transisi 2 tahun dinilai terlalu lama.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2024, 10, 17, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2022, 10, 17), "title": "UU PDP disahkan", "description": "Undang-Undang Pelindungan Data Pribadi disahkan DPR."},
            {"date": date(2024, 10, 17), "title": "UU PDP berlaku penuh", "description": "UU PDP mulai berlaku efektif setelah masa transisi."},
        ],
        "sources": [
            {"source_type": "official", "title": "UU No. 27 Tahun 2022 tentang Pelindungan Data Pribadi", "url": "https://jdih.setneg.go.id/", "snippet": "Teks resmi Undang-Undang Pelindungan Data Pribadi.", "site_name": "JDIH Setneg", "published_date": date(2022, 10, 17), "verification_status": "verified"},
            {"source_type": "news", "title": "UU PDP Resmi Berlaku, Ini yang Perlu Kamu Tahu", "url": "https://tekno.kompas.com/", "snippet": "Penjelasan lengkap hak-hak masyarakat terkait data pribadi.", "site_name": "Kompas Tekno", "published_date": date(2024, 10, 18), "verification_status": "needs_verification"},
        ],
    },
    {
        "title": "Program Keluarga Harapan (PKH) 2025",
        "status": "berlaku",
        "slug": "program-keluarga-harapan-pkh-2025",
        "category_slug": "bansos",
        "summary_30sec": "PKH 2025 memberikan bantuan tunai Rp800.000-Rp2.400.000 per tahun kepada keluarga miskin. Fokus pada kesehatan ibu dan anak serta pendidikan.",
        "summary_long": "Program Keluarga Harapan (PKH) dilanjutkan pada 2025 dengan peningkatan cakupan dan besaran. Komponen kesehatan (Ibu Hamil & Balita) Rp2.400.000/tahun, komponen pendidikan SD Rp800.000/tahun, SMP Rp1.200.000/tahun, SMA Rp1.600.000/tahun. Program menyasar sekitar 10 juta keluarga penerima manfaat.",
        "simple_explanation": "Apa itu PKH? Ini program bantuang uang dari pemerintah buat keluarga miskin. Yang dapat anak sekolah atau ibu hamil bisa dapet Rp800rb sampai Rp2,4 juta per tahun. Syaratnya apa? Keluarga miskin yang terdaftar di DTKS (Data Terpadu Kesehatan Sosial). Anak mereka harus sekolah atau ibunya hamil/nifas.",
        "impact_explanation": "Siapa yang terdampak: Keluarga miskin terdaftar di DTKS (sekitar 10 juta KRT)\nApa yang berubah: Besaran bantuan meningkat, cakupan diperluas\nKapan berlaku: Sepanjang 2025",
        "affected_groups": "Keluarga miskin, ibu hamil, anak usia sekolah",
        "government_claim": "PKH mengurangi kemiskinan dan mendorong investasi pada kesehatan dan pendidikan.",
        "public_criticism": "Masih banyak keluarga layak PKH yang tidak terdaftar di DTKS.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 1, 5, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2024, 12, 1), "title": "PKH 2025 diumumkan", "description": "Kemensos mengumumkan kelanjutan program PKH 2025."},
            {"date": date(2025, 1, 15), "title": "Penyaluran tahap I", "description": "Penyaluran bantuan PKH tahap pertama 2025."},
        ],
        "sources": [
            {"source_type": "official", "title": "PKH 2025: Komponen dan Besaran Bantuan", "url": "https://pkh.kemensos.go.id/", "snippet": "Informasi resmi program PKH 2025.", "site_name": "Kemensos", "published_date": date(2024, 12, 1), "verification_status": "verified"},
            {"source_type": "news", "title": "Cek Besaran PKH 2025, Ini Syarat dan Cara Daftar", "url": "https://www.liputan6.com/", "snippet": "Panduan lengkap penerimaan PKH 2025.", "site_name": "Liputan6", "published_date": date(2025, 1, 3), "verification_status": "needs_verification"},
        ],
    },
    {
        "title": "Stabilisasi Harga Pangan Strategis 2025",
        "status": "dibahas",
        "slug": "stabilisasi-harga-pangan-strategis-2025",
        "category_slug": "pangan",
        "summary_30sec": "Pemerintah membahas kebijakan stabilisasi harga pangan strategis (beras, cabai, bawang) melalui operasi pasar, impor tepat waktu, dan perbaikan rantai pasok dari petani ke konsumen.",
        "summary_long": "Kementerian Perdagangan dan Bulog mengajukan kebijakan stabilisasi harga pangan strategis yang mencakup: peningkatan stok buffer beras Bulog, pengetatan regulasi impor untuk mencegah harga anjlok, digitalisasi pasar modern di daerah, dan peningkatan infrastruktur logistik pangan. Kebijakan masih dibahas di DPR dan kementerian terkait.",
        "simple_explanation": "Apa yang dibahas? Pemerintah mau stabilin harga bahan makanan pokok kayak beras, cabai, dan bawang yang sering naik turun. Caranya apa? Stok beras Bulong ditambah, impor diatur lebih ketat, dan pasar diperbaiki. Kenapa ini penting? Karena harga pangan yang naik turun bikin masyarakat, terutama yang miskin, susah belanja. Dampaknya gimana? Kalau jalan, harga bahan pokok bisa lebih stabil. Tapi masih dalam pembahasan.",
        "impact_explanation": "Siapa yang terdampak: Seluruh konsumen, petani kecil, pedagang pasar\nApa yang berubah: Penambahan stok buffer, perbaikan rantai pasok\nKapan berlaku: Masih dibahas",
        "affected_groups": "Konsumen, petani kecil, pedagang",
        "government_claim": "Stabilisasi harga pangan strategis adalah prioritas untuk menjaga daya beli masyarakat.",
        "public_criticism": "Impor beras dinilai merugikan petani lokal. Operasi pasar hanya solusi jangka pendek.",
        "source_confidence": "medium",
        "verification_status": "needs_verification",
        "published_status": "draft",
    },
    {
        "title": "Tarif Angkutan Umum MRT dan LRT Jakarta 2025",
        "status": "berlaku",
        "slug": "tarif-angkutan-mrt-lrt-jakarta-2025",
        "category_slug": "transportasi",
        "summary_30sec": "Pemerintah DKI Jakarta menetapkan tarif integrasi MRT-LRT 2025 sebesar Rp8.500 untuk perjalanan pertama dan diskon 50% di jam padat. Program ini mendorong migrasi ke transportasi publik.",
        "summary_long": "Gubernur DKI Jakarta menetapkan tarif integrasi MRT dan LRT untuk 2025. Tarif awal Rp8.500 untuk perjalanan pertama di MRT, dengan potongan 50% pada jam padat (05.00-09.00 dan 16.00-20.00). Integrasi tiket elektronik MRT-LRT-BRT dimulai Maret 2025. Target penumpang MRT naik 30% dari 2024.",
        "simple_explanation": "Apa yang berubah? Tarif MRT-LRT Jakarta untuk 2025 tetap Rp8.500 buat awal naik. Tapi ada diskon 50% kalau kamu naek di jam padat. Tiketnya juga sekarang terintegrasi antara MRT, LRT, dan BRT. Kenapa? Pemerintah pengen lebih banyak orang pakai transportasi publik daripada mobil pribadi. Buat kamu apa? Lebih hemat dan gampang kalau naik transportasi umum se-Jakarta.",
        "impact_explanation": "Siapa yang terdampak: Pengguna MRT, LRT, dan BRT di Jakarta; komuter harian\nApa yang berubah: Diskon 50% jam padat, integrasi tiket\nKapan berlaku: Maret 2025",
        "affected_groups": "Komuter Jakarta, pekerja, pelajar",
        "government_claim": "Integrasi dan diskon tarif mendorong masyarakat beralih ke transportasi publik.",
        "public_criticism": "Jangkauan MRT-LRT masih terbatas. Masyarakat luar Jakarta belum terdampak positif.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 2, 1, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2025, 1, 15), "title": "Pengumuman tarif baru", "description": "DKI Jakarta mengumumkan tarif integrasi MRT-LRT 2025."},
            {"date": date(2025, 3, 1), "title": "Integrasi tiket dimulai", "description": "Tiket elektronik terintegrasi MRT-LRT-BRT mulai berlaku."},
        ],
        "sources": [
            {"source_type": "official", "title": "Tarif Integrasi MRT LRT Jakarta 2025", "url": "https://jakartamrt.co.id/", "snippet": "Informasi resmi tarif dan integrasi MRT Jakarta.", "site_name": "MRT Jakarta", "published_date": date(2025, 1, 15), "verification_status": "verified"},
            {"source_type": "news", "title": "MRT-LRT Jakarta Diskon 50% Jam Padat", "url": "https://megapolitan.kompas.com/", "snippet": "Detail diskon dan integrasi transportasi publik Jakarta.", "site_name": "Kompas Megapolitan", "published_date": date(2025, 1, 16), "verification_status": "needs_verification"},
        ],
    },
    {
        "title": "Subsidi FLPP Perumahan MBR 2025",
        "status": "berlaku",
        "slug": "subsidi-flpp-perumahan-mbr-2025",
        "category_slug": "perumahan",
        "summary_30sec": "Pemerintah menyediakan subsidi FLPP (Fasilitas Likuiditas Pembiayaan Perumahan) untuk rumah pertama MBR. KPR bunga efektif mulai 3,5% dengan harga rumah maksimal Rp214 juta di Jabodetabek.",
        "summary_long": "Program Fasilitas Likuiditas Pembiayaan Perumahan (FLPP) diperpanjang untuk 2025 dengan beberapa penyesuaian. Bunga KPR efektif mulai 3,5% untuk rumah pertama kelompok MBR (Masyarakat Berpenghasilan Rendah). Batas harga rumah di Jabodetabek Rp214 juta, luar Jabodetabek Rp168 juta. Program menyasar pekerja berpenghasilan maksimal Rp8 juta/bulan.",
        "simple_explanation": "Apa itu FLPP? Ini program pemerintah yang bikin KPR rumah pertama jadi lebih murah. Bunganya cuma 3,5% per tahun — jauh lebih murah dari KPR biasa yang 7-10%. Buat siapa? Buat keluarga berpenghasilan rendah yang belum punya rumah. Gaji maksimal Rp8 juta/bulan. Harga rumahnya berapa? Maksimal Rp214 juta di Jabodetabek, Rp168 juta di luar Jabodetabek.",
        "impact_explanation": "Siapa yang terdampak: MBR yang belum punya rumah, pekerja berpenghasilan <=Rp8juta/bulan\nApa yang berubah: KPR bunga 3,5%, batas harga rumah disesuaikan\nKapan berlaku: Sepanjang 2025",
        "affected_groups": "MBR, pekerja berpenghasilan rendah, keluarga baru",
        "government_claim": "FLPP membantu MBR memiliki rumah pertama dengan cicilan terjangkau.",
        "public_criticism": "Stok rumah FLPP terbatas dan lokasinya sering jauh dari pusat kerja. Proses pengajuan memakan waktu lama.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 1, 15, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2024, 11, 1), "title": "FLPP 2025 diumumkan", "description": "Kementerian PUPR mengumumkan kelanjutan program FLPP."},
            {"date": date(2025, 1, 1), "title": "FLPP 2025 berlaku", "description": "Program FLPP 2025 mulai berlaku dengan penyesuaian."},
        ],
        "sources": [
            {"source_type": "official", "title": "Program FLPP 2025: Syarat dan Cara Daftar", "url": "https://flppbtn.co.id/", "snippet": "Informasi resmi program FLPP perumahan MBR.", "site_name": "Kementerian PUPR", "published_date": date(2024, 11, 1), "verification_status": "verified"},
            {"source_type": "news", "title": "KPR FLPP 3,5%: Cara Daftar dan Syaratnya", "url": "https://properti.kompas.com/", "snippet": "Panduan lengkap pendaftaran KPR FLPP 2025.", "site_name": "Kompas Properti", "published_date": date(2025, 1, 5), "verification_status": "needs_verification"},
        ],
    },
    {
        "title": "Penghapusan Pajak Progresif Mobil Bekas",
        "status": "wacana",
        "slug": "penghapusan-pajak-progresif-mobil-bekas",
        "category_slug": "pajak",
        "summary_30sec": "Menteri Keuangan mengusulkan penghapusan pajak progresif kepemilikan mobil kedua dan seterusnya untuk mobil bekas. Tujuannya mendorong perputaran ekonomi otomotif.",
        "summary_long": "Kemenkeu mengajukan wacana penghapusan pajak progresif untuk kendaraan bekas. Saat ini, mobil kedua dikenakan pajak progresif hingga 4-10% dari Nilai Jual Kendaraan Bermotor. Wacana ini menyasar mobil bekas untuk mendorong perputaran ekonomi sektor otomotif. Masih dalam tahap kajian dan belum ada regulasi final.",
        "simple_explanation": "Apa yang diusulkan? Pajak progresif buat mobil kedua mau dihapus khususnya buat mobil bekas. Sekarang kalau kamu punya 2 mobil, mobil kedua kena pajak lebih tinggi. Usulannya pajak ini dihapus biar orang lebih mudah beli mobil bekas. Kenapa? Karena perputaran mobil bekah bisa dorong ekonomi. Dampaknya gimana? Belum pasti, masih dalam tahap wacana.",
        "impact_explanation": "Siapa yang terdampak: Pemilik kendaraan lebih dari satu, industri otomotif bekas\nApa yang berubah: Wacana penghapusan pajak progresif untuk mobil bekas\nKapan berlaku: Masih wacana, belum ada timeline",
        "affected_groups": "Pemilik kendaraan, dealer mobil bekas",
        "government_claim": "Penghapusan pajak progresif dapat mendorong perputaran ekonomi di sektor otomotif.",
        "public_criticism": "Bisa meningkatkan jumlah kendaraan di jalan dan memperburuk kemacetan.",
        "source_confidence": "low",
        "verification_status": "needs_verification",
        "published_status": "draft",
    },
    {
        "title": "Regulasi E-Commerce dan Perlindungan UMKM Digital",
        "status": "dibahas",
        "slug": "regulasi-e-commerce-perlindungan-umkm-digital",
        "category_slug": "umkm",
        "summary_30sec": "Pemerintah membahas regulasi baru untuk melindungi UMKM di platform e-commerce, termasuk batas maksimal diskon, kewajiban sertifikasi lokal, dan pembatasan produk impor langsung dari luar negeri.",
        "summary_long": "Kementerian Perdagangan dan Kominfo menyusun regulasi baru untuk platform e-commerce yang menyasar perlindungan UMKM. Poin utama: batasan diskon maksimal 80%, kewajiban sertifikasi SNI untuk produk lokal, pembatasan impor langsung dari platform asing, dan kewajiban transparansi algoritma rekomendasi. Regulasi masih dibahas di DPR.",
        "simple_explanation": "Apa yang mau diregulasi? Pemerintah mau bikin aturan baru buat e-commerce kayak Tokopedia, Shopee, dan sejenisnya. Aturannya antara lain: diskon maksimal 80%, produk harus punya sertifikasi, dan produk impor langsung dari luar negeri dibatasi. Kenapa? Banyak UMKM yang nggak bisa saingan sama produk murah dari luar negeri yang dijual langsung di platform. Dampaknya? UMKM lokal kayaknya bakal lebih dilindungi. Tapi konsumen bisa rugi kalau pilihan produk jadi lebih sedikit.",
        "impact_explanation": "Siapa yang terdampak: UMKM marketplace, pelaku e-commerce, konsumen\nApa yang berubah: Batasan diskon, sertifikasi produk, pembatasan impor langsung\nKapan berlaku: Masih dibahas DPR",
        "affected_groups": "UMKM, pelaku e-commerce, konsumen",
        "government_claim": "Regulasi melindungi UMKM dari persaingan tidak sehat dengan produk impor murah.",
        "public_criticism": "Konsumen khawatir pilihan produk berkurang dan harga naik. Platform menilai regulasi terlalu restriktif.",
        "source_confidence": "medium",
        "verification_status": "needs_verification",
        "published_status": "draft",
    },
    {
        "title": "Kurikulum Merdeka Implementasi Penuh 2025",
        "status": "berlaku",
        "slug": "kurikulum-merdeka-implementasi-penuh-2025",
        "category_slug": "pendidikan",
        "summary_30sec": "Kurikulum Merdeka diimplementasikan penuh di seluruh satuan pendidikan mulai tahun ajaran 2025/2026. Sekolah boleh menyesuaikan 20% jam pelajaran dengan konteks lokal.",
        "summary_long": "Kemendikbudristek menetapkan implementasi penuh Kurikulum Merdeka untuk tahun ajaran 2025/2026 di seluruh jenjang. Fitur utama: 20% jam pelajaran bisa disesuaikan konteks lokal, asesmen berbasis kompetensi, proyek penguatan profil pelajar Pancasila, dan fleksibilitas modul ajar. Pemerintah menyediakan pelatihan dan platform Merdeka Mengajar.",
        "simple_explanation": "Apa itu Kurikulum Merdeka? Ini kurikulum baru yang ngasih sekolah lebih banyak kebebasan buat tentuin cara ngajarnya. 20% jam pelajaran bisa dipakai buat hal yang relevan sama daerah masing-masing. Kenapa berubah? Pemerintah pengen pendidikan nggak cuma soal hafalan, tapi juga soal skill dan karakter. Dampaknya? Guru harus adaptasi dan butuh pelatihan. Ada yang seneng karena lebih fleksibel, ada yang bingung.",
        "impact_explanation": "Siapa yang terdampak: Guru, siswa, dan satuan pendidikan di seluruh Indonesia\nApa yang berubah: Implementasi penuh, 20% jam pelajaran fleksibel\nKapan berlaku: Tahun ajaran 2025/2026",
        "affected_groups": "Guru, siswa, orang tua, satuan pendidikan",
        "government_claim": "Kurikulum Merdeka memberi fleksibilitas kepada sekolah dan mengembangkan kompetensi siswa.",
        "public_criticism": "Banyak guru belum siap dan pelatihan tidak merata. Infrastruktur sekolah tidak memadai.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 1, 10, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2022, 7, 1), "title": "Kurikulum Merdeka mulai diuji coba", "description": "Implementasi awal di sekolah penggerak."},
            {"date": date(2025, 7, 1), "title": "Implementasi penuh", "description": "Kurikulum Merdeka berlaku di seluruh satuan pendidikan."},
        ],
        "sources": [
            {"source_type": "official", "title": "Kurikulum Merdeka: Panduan Implementasi 2025", "url": "https://kurikulum.kemdikbud.go.id/", "snippet": "Panduan resmi implementasi Kurikulum Merdeka.", "site_name": "Kemendikbudristek", "published_date": date(2024, 12, 1), "verification_status": "verified"},
            {"source_type": "news", "title": "Kurikulum Merdeka 2025: Apa yang Berubah?", "url": "https://edukasi.kompas.com/", "snippet": "Ringkasan perubahan Kurikulum Merdeka untuk 2025.", "site_name": "Kompas Edukasi", "published_date": date(2025, 1, 5), "verification_status": "needs_verification"},
        ],
    },
    {
        "title": "Kenaikan Harga BBM Subsidi Pertamina 2025",
        "status": "ditunda",
        "slug": "kenaikan-harga-bbm-subsidi-pertamina-2025",
        "category_slug": "ekonomi",
        "summary_30sec": "Rencana kenaikan harga BBM jenis Pertalite dan Solar ditunda. Pemerintah memilih menambah alokasi subsidi anggaran daripada menaikkan harga di tengah tekanan ekonomi.",
        "summary_long": "Pemerintah sempat mengkaji kenaikan harga BBM subsidi (Pertalite dan Solar) untuk mengurangi beban anggaran. Namun, keputusan ditunda setelah pertimbangan politik dan sosial. Pemerintah memilih menambah alokasi subsidi sebesar Rp59 triliun untuk menutup selisih harga. Kebijakan ini bersifat sementara dan akan dikaji ulang di tengah tahun.",
        "simple_explanation": "Apa yang terjadi? Pemerintah mau naikin harga BBM subsidi (Pertalite dan Solar), tapi akhirnya ditunda. Daripada naikin harga, pemerintah tambah aja anggaran subsidi sebesar Rp59 triliun. Kenapa ditunda? Karena naikin harga BBM waktu ekonomi lagi susah bikin masyarakat tambah merasa berat. Dampaknya? BBM subsidi harga tetap buat sekarang. Tapi anggaran subsidi bikin defisit negara makin besar.",
        "impact_explanation": "Siapa yang terdampak: Pengguna BBM subsidi (Pertalite, Solar), angkutan umum, UMKM\nApa yang berubah: Harga BBM subsidi tetap, subsidi anggaran ditambah Rp59T\nKapan berlaku: Ditunda tanpa timeline pasti",
        "affected_groups": "Pengguna kendaraan, angkutan umum, UMKM",
        "government_claim": "Penundaan kenaikan BBM untuk menjaga daya beli masyarakat di tengah tekanan ekonomi.",
        "public_criticism": "Subsidi BBM dinilai tidak tepat sasaran dan membebani anggaran negara.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 3, 1, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2025, 1, 15), "title": "Rencana kenaikan BBM diusulkan", "description": "Kemenkeu mengusulkan penyesuaian harga BBM subsidi."},
            {"date": date(2025, 2, 20), "title": "Kenaikan ditunda", "description": "Pemerintah memutuskan menambah subsidi alih-alih menaikkan harga."},
        ],
        "sources": [
            {"source_type": "official", "title": "Pemerintah Tambah Subsidi BBM Rp59T", "url": "https://www.kemenkeu.go.id/", "snippet": "Penjelasan resmi penambahan alokasi subsidi BBM.", "site_name": "Kemenkeu", "published_date": date(2025, 2, 20), "verification_status": "verified"},
            {"source_type": "news", "title": "Harga BBM Subsidi Tidak Naik, Begini Alasannya", "url": "https://www.cnbindonesia.com/", "snippet": "Analisis keputusan penundaan kenaikan BBM.", "site_name": "CNN Indonesia", "published_date": date(2025, 2, 21), "verification_status": "needs_verification"},
        ],
    },
    {
        "title": "Program Bantuan Listrik dan Gas Masyarakat Miskin",
        "status": "berlaku",
        "slug": "program-bantuan-listrik-gas-masyarakat-miskin",
        "category_slug": "bansos",
        "summary_30sec": "Pemerintah menyediakan subsidi listrik 900VA untuk 33,6 juta rumah tangga dan tabung gas 3kg bersubsidi. Program ini menyasar keluarga miskin dan rentan.",
        "summary_long": "Program subsidi energi untuk masyarakat miskin terdiri dari dua komponen: subsidi listrik 900VA untuk 33,6 juta rumah tangga dan penyediaan LPG 3kg bersubsidi. Pemerintah mengalokasikan anggaran sekitar Rp52 triliun untuk subsidi listrik dan Rp77 triliun untuk LPG 3kg. Penyaluran melalui PLN dan pangkalan gas bersubsidi.",
        "simple_explanation": "Apa bantuannya? Pemerintah kasih subsidi listrik buat rumah tangga miskin (pakai meteran 900VA) dan gas elpiji 3kg yang harganya lebih murah dari pasar. Buat siapa? Keluarga miskin dan rentan yang udah terdaftar di DTKS.",
        "impact_explanation": "Siapa yang terdampak: 33,6 juta rumah tangga listrik 900VA, pengguna gas 3kg\nApa yang berubah: Subsidi tetap diberikan, harga listrik dan gas subsidi tidak naik\nKapan berlaku: Sepanjang 2025",
        "affected_groups": "Keluarga miskin, pengguna listrik 900VA, pelanggan LPG 3kg",
        "government_claim": "Subsidi energi meringankan beban masyarakat miskin dan menjaga stabilitas harga kebutuhan pokok.",
        "public_criticism": "Subsidi LPG 3kg banyak bocor dan tidak tepat sasaran.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 1, 5, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2025, 1, 1), "title": "Subsidi listrik dan gas 2025 berlaku", "description": "Program subsidi energi untuk masyarakat miskin dilanjutkan."},
        ],
        "sources": [
            {"source_type": "official", "title": "Subsidi Listrik 900VA dan LPG 3kg 2025", "url": "https://www.kemenkeu.go.id/", "snippet": "Informasi alokasi subsidi energi.", "site_name": "Kemenkeu", "published_date": date(2025, 1, 1), "verification_status": "verified"},
        ],
    },
    {
        "title": "Pengetatan Impor Beras oleh BULOG",
        "status": "dibahas",
        "slug": "pengetatan-impor-beras-bulog",
        "category_slug": "pangan",
        "summary_30sec": "BULOG mengajukan pengetatan kuota impor beras untuk melindungi petani lokal. Wacana ini memicu perdebatan antara menjaga harga petani vs menjaga pasokan dan harga konsumen.",
        "summary_long": "BULOG mengajukan rencana pengetatan impor beras untuk menjaga stabilitas harga gabah di tingkat petani. Kuota impor beras 2025 diusulkan dikurangi 30% dari tahun sebelumnya. Namun, hal ini menuai kritik karena bisa mengancam pasokan dan menaikkan harga beras di pasar konsumen. Kementerian Perdagangan masih mengkaji keseimbangan antara perlindungan petani dan ketersediaan pangan.",
        "simple_explanation": "Apa yang dibahas? BULOG mau kurangi impor beras supaya harga di tingkat petani stabil. Tapi kalau impor dikurangi, beras di pasar bisa langka dan mahal. Jadi ada perdebatan: lindungi petani atau lindungi konsumen?",
        "impact_explanation": "Siapa yang terdampak: Petani padi, konsumen beras, BULOG\nApa yang berubah: Kuota impor beras diusulkan dikurangi 30%\nKapan berlaku: Masih dibahas",
        "affected_groups": "Petani padi, konsumen, pedagang beras",
        "government_claim": "Pengetatan impor melindungi harga gabah petani dan mendorong kedaulatan pangan.",
        "public_criticism": "Mengurangi impor bisa meningkatkan harga beras di konsumen.",
        "source_confidence": "medium",
        "verification_status": "needs_verification",
        "published_status": "draft",
    },
    {
        "title": "Pembangunan Jalan Tol Trans Sumatera",
        "status": "dibahas",
        "slug": "pembangunan-jalan-tol-trans-sumatera",
        "category_slug": "infrastruktur",
        "summary_30sec": "Proyek Jalan Tol Trans Sumatera masih berlanjut dengan beberapa ruas dalam tahap pembangunan. Pemerintah mengalokasikan anggaran lanjutan untuk akselerasi penyelesaian ruas prioritas.",
        "summary_long": "Pembangunan Jalan Tol Trans Sumatera dilanjutkan pada 2025 dengan fokus pada ruas-ruas prioritas yang menghubungkan banda Aceh hingga Lampung. Beberapa ruas sudah beroperasi, sementara lainnya masih dalam pembangunan. Pemerintah mengalokasikan anggaran lanjutan dari APBN dan skema KPBU untuk akselerasi.",
        "simple_explanation": "Apa yang sedang dibangun? Jalan tol yang menghubungkan ujung utara sampai selatan Sumatera. Tujuannya supaya perjalanan antar kota di Sumatera lebih cepat. Ada beberapa ruasan yang udah jalan, ada yang masih dibangun.",
        "impact_explanation": "Siapa yang terdampak: Pengguna jalan di Sumatera, industri logistik, ekonomi regional\nApa yang berubah: Ruas tol baru beroperasi, kemacetan berkurang\nKapan berlaku: Progresif hingga 2028",
        "affected_groups": "Pengguna jalan, transportasi logistik",
        "government_claim": "Tol Trans Sumatera mempercepat konektivitas dan pertumbuhan ekonomi di Sumatera.",
        "public_criticism": "Proyek dinilai lambat dan biaya pembangunan membengkak.",
        "source_confidence": "medium",
        "verification_status": "needs_verification",
        "published_status": "draft",
    },
    {
        "title": "UU Penanganan Stunting dan Gizi Buruk",
        "status": "disahkan",
        "slug": "uu-penanganan-stunting-gizi-buruk",
        "category_slug": "kesehatan",
        "summary_30sec": "UU tentang Penanganan Stunting dan Gizi Buruk disahkan DPR. UU ini mewajibkan pemerintah pusat dan daerah menyediakan intervensi gizi, pemantauan tumbuh kembang, dan air bersih untuk mengurangi prevalensi stunting.",
        "summary_long": "Undang-Undang tentang Penanganan Stunting dan Gizi Buruk disahkan DPR pada 2024. UU ini mengamanatkan intervensi spesifik seperti suplementasi gizi, pemantauan tumbuh kembang anak, penyediaan air bersih dan sanitasi, serta edukasi gizi. Pemerintah daerah wajib mengalokasikan anggaran untuk penanganan stunting. Target prevalensi stunting turun di bawah 14% pada 2025.",
        "simple_explanation": "Apa itu UU ini? Undang-undang baru yang wajibin pemerintah atasin stunting dan gizi buruk anak. Caranya: kasih makanan bergizi gratis di posyandu, pantau pertumbuhan anak, dan sediain air bersih.",
        "impact_explanation": "Siapa yang terdampak: Balita dan anak stunting, keluarga miskin, petugas kesehatan\nApa yang berubah: Intervensi gizi wajib, alokasi anggaran daerah untuk stunting\nKapan berlaku: Setelah diundangkan",
        "affected_groups": "Balita, keluarga miskin, petugas kesehatan",
        "government_claim": "UU ini memastikan penanganan stunting menjadi prioritas nasional dan daerah.",
        "public_criticism": "Implementasi di daerah tertentu masih lemah. Data stunting sering tidak akurat.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2024, 11, 1, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2024, 7, 10), "title": "RUU Stunting dibahas DPR", "description": "DPR membahas RUU Penanganan Stunting dan Gizi Buruk."},
            {"date": date(2024, 10, 15), "title": "UU disahkan", "description": "UU Penanganan Stunting disahkan oleh DPR."},
        ],
        "sources": [
            {"source_type": "official", "title": "UU Penanganan Stunting dan Gizi Buruk", "url": "https://dpr.go.id/", "snippet": "Teks RUU/UU tentang penanganan stunting.", "site_name": "DPR RI", "published_date": date(2024, 10, 15), "verification_status": "verified"},
        ],
    },
    {
        "title": "Peraturan PSE Asing dan Lokalisasi Data",
        "status": "berlaku",
        "slug": "peraturan-pse-asing-lokalisasi-data",
        "category_slug": "digital-teknologi",
        "summary_30sec": "Peraturan mewajibkan PSE asing mendaftar ke Kominfo dan menyimpan data pengguna Indonesia di data center domestik. Pelanggaran bisa dikenai sanksi administratif hingga pemblokiran.",
        "summary_long": "Peraturan PSE asing mewajibkan penyelenggara sistem elektronik yang beroperasi di Indonesia untuk mendaftar ke Kominfo, menyimpan data pengguna Indonesia di data center domestik, dan menunjuk perwakilan hukum di Indonesia. Platform yang tidak mematuhi dapat dikenai sanksi berupa teguran tertulis, denda, hingga pemblokiran. Regulasi ini berlaku untuk platform seperti Google, Meta, TikTok, dan lainnya.",
        "simple_explanation": "Apa yang diatur? Perusahaan teknologi asing kayak Google, Meta, dan TikTok harus daftar ke Kominfo dan simpan data orang Indonesia di Indonesia. Nggak daftar? Bisa diblokir. Kenapa? Biar data orang Indonesia nggak kabur ke luar negeri dan pemerintah bisa ngawasin. Dampaknya? Perusahaan asing harus bangun data center di Indonesia — itu mahal. Tapi data kita jadi lebih aman katanya.",
        "impact_explanation": "Siapa yang terdampak: PSE asing (Google, Meta, TikTok dll), pengguna layanan digital\nApa yang berubah: Kewajiban registrasi dan lokalisasi data\nKapan berlaku: Sudah berlaku efektif",
        "affected_groups": "PSE asing, pengguna digital Indonesia",
        "government_claim": "Regulasi melindungi data pribadi warga negara Indonesia dan memberikan yurisdiksi hukum.",
        "public_criticism": "Biana data center lokal sangat tinggi. Beberapa platform memilih keluar dari Indonesia daripada mematuhi.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2024, 7, 20, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2022, 7, 20), "title": "Peraturan PSE mulai berlaku", "description": "Peraturan tentang PSE mulai berlaku dan mewajibkan registrasi."},
            {"date": date(2024, 3, 1), "title": "Deadline lokalisasi data", "description": "Deadline penyimpanan data pengguna Indonesia di data center domestik."},
        ],
        "sources": [
            {"source_type": "official", "title": "Peraturan PSE dan Lokalisasi Data", "url": "https://kominfo.go.id/", "snippet": "Regulasi PSE dari Kementerian Kominfo.", "site_name": "Kominfo", "published_date": date(2022, 7, 20), "verification_status": "verified"},
        ],
    },
    {
        "title": "Revisi UU Cipta Kerja (Omnibus Law) Pasal Ketenagakerjaan",
        "status": "dibahas",
        "slug": "revisi-uu-cipta-kerja-pasal-ketenagakerjaan",
        "category_slug": "tenaga-kerja",
        "summary_30sec": "DPR membahas revisi UU Cipta Kerja khususnya pasal ketenagakerjaan. Poin kontroversi: perubahan aturan PHK, upah minimum, dan kontrak kerja. Serikat buruh menolak revisi yang dianggap merugikan pekerja.",
        "summary_long": "Revisi Undang-Undang Cipta Kerja pada pasal ketenagakerjaan menjadi topik hangat di DPR. Beberapa pasal yang direvisi meliputi: perubahan definisi upah, penyesuaian aturan PHK, revisi aturan kontrak kerja alih fungsi (outsourcing), dan penyesuaian kompensasi masa kerja. Serikat buruh menolak revisi yang dianggap merugikan pekerja, sementara pengusaha mendukung fleksibilitas ketenagakerjaan.",
        "simple_explanation": "Apa yang direvisi? UU Cipta Kerja bagian ketenagakerjaan mau direvisi. Yang dibahas antara lain: aturan PHK, upah minimum, dan kontrak kerja. Buruh menolak karena dianggap merugikan pekerja. Pengusaha dukung karena pengen lebih fleksibel. Dampaknya? Kalau direvisi, aturan kerja bisa berubah. Tapi masih belum final, masih debat di DPR.",
        "impact_explanation": "Siapa yang terdampak: Seluruh pekerja formal di Indonesia, pengusaha, serikat buruh\nApa yang berubah: Aturan PHK, upah minimum, outsourcing (masih dibahas)\nKapan berlaku: Masih dalam proses legislasi",
        "affected_groups": "Pekerja formal, pengusaha, serikat buruh",
        "government_claim": "Revisi dimaksudkan untuk menciptakan iklim investasi yang lebih baik sambil melindungi hak pekerja.",
        "public_criticism": "Serikat buruh menilai revisi melemahkan perlindungan pekerja, terutama soal PHK dan outsourcing.",
        "source_confidence": "medium",
        "verification_status": "needs_verification",
        "published_status": "draft",
    },
    {
        "title": "Penyesuaian PPh Final UMKM 0,5%",
        "status": "berlaku",
        "slug": "penyesuaian-pph-final-umkm-05-persen",
        "category_slug": "umkm",
        "summary_30sec": "PPnBM UMKM dengan omzet di bawah Rp4,8 miliar dikenakan PPh Final 0,5% berdasarkan PP 55/2022. Perpanjangan fasilitas ini dilanjutkan untuk 2025.",
        "summary_long": "Pemerintah memperpanjang fasilitas PPh Final 0,5% untuk UMKM dengan omzet tahunan di bawah Rp4,8 miliar berdasarkan PP 55/2022. Fasilitas ini berlaku selama 7 tahun dari permulaan usaha. Perpanjangan memastikan UMKM yang sudah mendapatkan fasilitas tidak langsung kena tarif normal setelah 3 tahun.",
        "simple_explanation": "Apa itu PPh 0,5% buat UMKM? Kalau omzet usahamu di bawah Rp4,8 miliar per tahun, kamu cuma bayar pajak 0,5% dari omzet. Nggak perlu hitung laba-rugi yang rumit. Kenapa? Biar UMKM gampang ngurus pajak dan nggak berat. Dampaknya? UMKM lebih ringan bayar pajaknya. Tapi setelah 7 tahun, tarifnya balik normal.",
        "impact_explanation": "Siapa yang terdampak: UMKM dengan omzet < Rp4,8 miliar/tahun\nApa yang berubah: PPh Final 0,5% diperpanjang\nKapan berlaku: Sepanjang 2025",
        "affected_groups": "UMKM, pelaku usaha kecil",
        "government_claim": "Fasilitas PPh 0,5% membantu UMKM mengurus pajak dengan mudah dan meringankan beban pajak.",
        "public_criticism": "Batas omzet Rp4,8 miliar dinilai terlalu tinggi sehingga menutupi perusahaan menengah.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 1, 5, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2022, 9, 1), "title": "PP 55/2022 ditetapkan", "description": "Peraturan Pemerintah tentang PPh Final UMKM ditetapkan."},
            {"date": date(2025, 1, 1), "title": "Perpanjangan fasilitas", "description": "Fasilitas PPh 0,5% diperpanjang untuk 2025."},
        ],
        "sources": [
            {"source_type": "official", "title": "PP No. 55 Tahun 2022 tentang PPh Final UMKM", "url": "https://jdih.setneg.go.id/", "snippet": "Peraturan Pemerintah tentang PPh Final UMKM.", "site_name": "JDIH Setneg", "published_date": date(2022, 9, 1), "verification_status": "verified"},
        ],
    },
    {
        "title": "Pengadaan Vaksin COVID-19 Booster 2025",
        "status": "dibatalkan",
        "slug": "pengadaan-vaksin-covid-19-booster-2025",
        "category_slug": "kesehatan",
        "summary_30sec": "Program vaksinasi COVID-19 booster resmi dihentikan pada 2024. Pemerintah tidak lagi mengalokasikan anggaran untuk pengadaan vaksin COVID-19 booster pada 2025.",
        "summary_long": "Kementerian Kesehatan resmi menghentikan program vaksinasi COVID-19 booster pada akhir 2024. Kesepakatan WHO bahwa pandemi COVID-19 telah berakhir menjadi dasar kebijakan ini. Stok vaksin yang tersisa akan dimanfaatkan untuk program vaksinasi rutin lainnya. Tidak ada alokasi anggaran baru untuk pengadaan vaksin COVID-19 pada 2025.",
        "simple_explanation": "Apa yang terjadi? Program vaksin COVID booster udah dihentikan. Pemerintah nggak beli vaksin COVID lagi buat 2025. Kenapa? Karena WHO bilang pandemi udah berakhir dan kasus COVID udah makin sedikit.",
        "impact_explanation": "Siapa yang terdampak: Masyarakat yang ingin vaksinasi booster COVID-19\nApa yang berubah: Program vaksinasi booster dihentikan, stok tersisa dipakai untuk program lain\nKapan: Berlaku sejak akhir 2024",
        "affected_groups": "Masyarakat umum",
        "government_claim": "Pandemi COVID-19 telah berakhir, vaksinasi rutin cukup untuk perlindungan dasar.",
        "public_criticism": "Sebagian kelompok rentan meminta vaksinasi booster tetap tersedia secara sukarela.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2024, 12, 1, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2023, 5, 5), "title": "WHO nyatakan pandemi berakhir", "description": "WHO secara resmi menyatakan pandemi COVID-19 tidak lagi menjadi darurat."},
            {"date": date(2024, 12, 31), "title": "Program vaksinasi booster dihentikan", "description": "Pemerintah menghentikan program vaksinasi COVID-19 booster."},
        ],
        "sources": [
            {"source_type": "official", "title": "Penghentian Program Vaksinasi COVID-19 Booster", "url": "https://www.kemkes.go.id/", "snippet": "Surat edaran penghentian program vaksinasi booster.", "site_name": "Kemenkes", "published_date": date(2024, 11, 15), "verification_status": "verified"},
        ],
    },
    {
        "title": "Subsidi Pupuk untuk Petani 2025",
        "status": "berlaku",
        "slug": "subsidi-pupuk-untuk-petani-2025",
        "category_slug": "pangan",
        "summary_30sec": "Pemerintah mengalokasikan subsidi pupuk sebesar Rp17,9 triliun untuk 2025. Pupuk bersubsidi hanya tersedia untuk petani terdaftar di SIMLUTAN dan限额 distribusi 9,45 juta ton.",
        "summary_long": "Alokasi subsidi pupuk 2025 ditetapkan sebesar Rp17,9 triliun dengan distribusi maksimal 9,45 juta ton. Pupuk bersubsidi hanya diberikan kepada petani yang terdaftar di Sistem Informasi Manajemen Subsidi Pupuk (SIMLUTAN). Jenis pupuk bersubsidi meliputi urea, SP-36, ZA, NPK, dan organic. Distribusi diprioritaskan untuk komoditas pangan strategis.",
        "simple_explanation": "Apa bantuannya? Pemerintah kasih pupuk murah buat petani yang udah terdaftar. Total anggarannya Rp17,9 triliun. Tapi ingat, pupuk bersubsidi cuma buat petani yang terdaftar di SIMLUTAN, bukan sembarang orang.",
        "impact_explanation": "Siapa yang terdampak: Petani terdaftar di SIMLUTAN\nApa yang berubah: Alokasi Rp17,9T untuk 9,45 juta ton pupuk bersubsidi\nKapan berlaku: Musim tanam 2025",
        "affected_groups": "Petani padi, petani hortikultura",
        "government_claim": "Subsidi pupuk membantu petani menekan biaya produksi dan menjaga produktivitas pangan.",
        "public_criticism": "Distribusi sering tidak merata. Petani di daerah terpencil kesulitan mengakses pupuk bersubsidi.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 1, 10, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2024, 12, 15), "title": "Alokasi subsidi pupuk 2025 ditetapkan", "description": "Pemerintah menetapkan alokasi subsidi pupuk 9,45 juta ton."},
            {"date": date(2025, 1, 1), "title": "Distribusi dimulai", "description": "Distribusi pupuk bersubsidi musim tanam 2025 dimulai."},
        ],
        "sources": [
            {"source_type": "official", "title": "Alokasi Subsidi Pupuk 2025", "url": "https://www.pertanian.go.id/", "snippet": "Informasi resmi alokasi subsidi pupuk.", "site_name": "Kementerian Pertanian", "published_date": date(2024, 12, 15), "verification_status": "verified"},
        ],
    },
    {
        "title": "Penetapan Upah Minimum Kabupaten/Kota 2025",
        "status": "berlaku",
        "slug": "penetapan-umk-2025",
        "category_slug": "tenaga-kerja",
        "summary_30sec": "UMK 2025 ditetapkan oleh masing-masing gubernur. Rata-rata kenaikan 6,5% mengikuti formula baru PP 51/2024. Setiap kabupaten/kota memiliki nominal berbeda.",
        "summary_long": "Penetapan Upah Minimum Kabupaten/Kota (UMK) 2025 mengikuti formula baru dalam PP 51/2024. Setiap gubernur menetapkan UMK berdasarkan rekomendasi Dewan Pengupahan dan considering inflasi, pertumbuhan ekonomi, dan indeks paritas daya beli. Kenaikan rata-rata nasional sekitar 6,5%, namun bervariasi per daerah.",
        "simple_explanation": "Apa yang baru? Setiap daerah sekarang punya UMK (Upah Minimum Kabupaten/Kota) masing-masing yang ditetapkan gubernur. Kenaikan rata-rata 6,5% dari tahun lalu.",
        "impact_explanation": "Siapa yang terdampak: Pekerja bergaji minimum di setiap daerah\nApa yang berubah: UMK naik rata-rata 6,5%, formula baru\nKapan berlaku: 1 Januari 2025",
        "affected_groups": "Pekerja bergaji minimum, UMKM",
        "government_claim": "Formula baru lebih adil dan mempertimbangkan daya beli pekerja.",
        "public_criticism": "Beberapa serikat buruh menilai kenaikan belum mencukupi kebutuhan hidup layak.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 1, 1, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2024, 11, 30), "title": "Gubernur menetapkan UMK", "description": "Seluruh gubernur menetapkan UMK 2025."},
            {"date": date(2025, 1, 1), "title": "UMK berlaku", "description": "Upah Minimum Kabupaten/Kota berlaku efektif."},
        ],
        "sources": [
            {"source_type": "official", "title": "Keputusan Gubernur tentang UMK 2025", "url": "https://kemnaker.go.id/", "snippet": "Surat keputusan gubernur tentang UMK.", "site_name": "Kemnaker", "published_date": date(2024, 11, 30), "verification_status": "verified"},
        ],
    },
    {
        "title": "Program Rumah Susun Sewa (Rusunawa) untuk Pekerja",
        "status": "wacana",
        "slug": "program-rusunawa-untuk-pekerja",
        "category_slug": "perumahan",
        "summary_30sec": "Kementerian PUPR mengusulkan pembangunan rusunawa khusus pekerja di kawasan industri. Wacana ini menargetkan 50.000 unit di 10 kota industri prioritas.",
        "summary_long": "Kementerian PUPR mengusulkan program pembangunan rumah susun sewa (rusunawa) khusus pekerja di kawasan индустри. Wacana menargetkan pembangunan 50.000 unit di 10 kota industri prioritas. Biaya sewa ditargetkan Rp300.000-Rp500.000 per bulan. Program ini masih dalam tahap kajian dan belum ada alokasi anggaran definitif.",
        "simple_explanation": "Apa yang diusulkan? Pemerintah mau bangun apartemen susun murah buat pekerja di daerah industri. Sewanya sekitar Rp300rb-500rb per bulan. Buat siapa? Pekerja yang kerja di daerah industri dan belum punya rumah. Masih wacana loh, belum pasti.",
        "impact_explanation": "Siapa yang terdampak: Pekerja di kawasan industri, pekerja migran\nApa yang berubah: Wacana rusunawa murah Rp300-500rb/bulan\nKapan berlaku: Masih wacana",
        "affected_groups": "Pekerja industri, pekerja migran",
        "government_claim": "Rusunawa pekerja mengurangi beban tempat tinggal dan meningkatkan produktivitas.",
        "public_criticism": "Kualitas rusunawa sering buruk. Lokasi terlalu jauh dari fasilitas umum.",
        "source_confidence": "low",
        "verification_status": "needs_verification",
        "published_status": "draft",
    },
    {
        "title": "Pengetatan Aturan Impor Barang Bekas dan Pakai",
        "status": "dibahas",
        "slug": "pengetatan-aturan-impor-barang-bekas",
        "category_slug": "ekonomi",
        "summary_30sec": "Kementerian Perdagangan membahas pengetatan aturan impor barang bekas seperti pakaian dan sepatu untuk melindungi industri lokal. THR agar impor barang bekas dilarang total.",
        "summary_long": "Kementerian Perdagangan mengusulkan pengetatan aturan impor barang bekas terutama pakaian dan sepatu. Usulan meliputi pelarangan impor pakaian bekas, pengetatan SNI untuk produk impor, dan peningkatan pengawasan di pelabuhan. Dialog dengan industri lokal dan asosiasi importir masih berlangsung.",
        "simple_explanation": "Apa yang dibahas? Pemerintah mau ketatkin aturan impor barang bekas (pakaian, sepatu second). Ada yang mau dilarang total. Kenapa? Karena barang bekas dari luar negeri bikin industri lokal kalah saing. Dampaknya? Kalau dilarang, industri lokal mungkin bisa bangkit. Tapi harga pakaian bisa naik buat yang biasa beli second.",
        "impact_explanation": "Siapa yang terdampak: Industri tekstil lokal, pedagang pakaian bekas, konsumen low-income\nApa yang berubah: Potensi pelarangan impor pakaian bekas\nKapan berlaku: Masih dibahas",
        "affected_groups": "Industri tekstil, pedagang loak, konsumen",
        "government_claim": "Pengetatan impor melindungi industri tekstil dan penciptaan lapangan kerja lokal.",
        "public_criticism": "Pelarangan bisa menaikkan harga pakaian dan mengurangi akses masyarakat miskin.",
        "source_confidence": "medium",
        "verification_status": "needs_verification",
        "published_status": "draft",
    },
    {
        "title": "Pembangunan Ibu Kota Nusantara (IKN) Fase Prioritas",
        "status": "dibahas",
        "slug": "pembangunan-ikn-fase-prioritas",
        "category_slug": "infrastruktur",
        "summary_30sec": "Pembangunan IKN memasuki fase prioritas dengan fokus pada infrastruktur dasar, istana kepresidenan, dan area pemerintahan. Anggaran revisi 2025 mengalokasikan dana lanjutan untuk akselerasi.",
        "summary_long": "Pembangunan Ibu Kota Nusantara (IKN) memasuki fase prioritas setelah seremoni awal 2024. Fokus pembangunan meliputi istana kepresidenan, area legislatif, infrastruktur jalan, penyediaan air bersih, dan perumahan ASN fase 1. Anggaran revisi 2025 mengalokasikan dana lanjutan. Kritik terhadap keterlambatan dan pembengkakan biaya masih berlanjut.",
        "simple_explanation": "Apa yang dibangun? Ibu kota baru Indonesia di Kalimantan Timur namanya IKN. Sekarang lagi dibangun jalan, istana, dan perumahan buat pegawai negeri. Masih banyak yang belum kelar dan anggarannya besar banget.",
        "impact_explanation": "Siapa yang terdampak: ASN yang akan pindah, masyarakat Kalimantan Timur, pembayar pajak\nApa yang berubah: Pembangunan infrastruktur dasar IKN berlanjut\nKapan: Fase prioritas 2024-2029",
        "affected_groups": "ASN, masyarakat Kalimantan Timur",
        "government_claim": "IKN menjadi simbol pembangunan merata dan pengurangan ketimpangan antar wilayah.",
        "public_criticism": "Anggaran IKN dinilai terlalu besar dan mengorbankan pembangunan daerah lain.",
        "source_confidence": "medium",
        "verification_status": "needs_verification",
        "published_status": "draft",
    },
    {
        "title": "Reformasi Biaya Administrasi Perbankan",
        "status": "disahkan",
        "slug": "reformasi-biaya-administrasi-perbankan",
        "category_slug": "digital-teknologi",
        "summary_30sec": "BI dan OJK menyetujui penurunan biaya admin rekening bank dan transfer antar bank. Biaya transfer RI-Pay dikurangi dan biaya admin tabungan dibatasi maksimal Rp10.000/bulan.",
        "summary_long": "Bank Indonesia dan OJK menyetujui paket reformasi biaya perbankan yang meliputi: penurunan biaya administrasi rekening tabungan maksimal Rp10.000/bulan untuk saldo di bawah Rp1 juta, penghapusan biaya transfer antar bank melalui BI-FAST untuk nominal di bawah Rp10 juta, dan peningkatan batas BI-FAST tanpa biaya.",
        "simple_explanation": "Apa yang berubah? Biaya admin tabungan dibatasi maksimal Rp10.000/bulan buat saldo kecil. Transfer antar bank jadi lebih murah atau gratis buat nominal di bawah Rp10 juta. Kenapa? Pemerintah mau perbankan lebih murah buat orang kecil.",
        "impact_explanation": "Siapa yang terdampak: Nasabah bank, terutama pemilik rekening saldo kecil\nApa yang berubah: Biaya admin tabungan dibatasi, transfer BI-FAST gratis\nKapan berlaku: Bertahap sepanjang 2025",
        "affected_groups": "Nasabah bank, UMKM",
        "government_claim": "Reformasi biaya perbankan mengurangi beban masyarakat dan mendorong inklusi keuangan.",
        "public_criticism": "Implementasi tidak seragam di semua bank. Beberapa bank masih mengenakan biaya tersembunyi.",
        "source_confidence": "high",
        "verification_status": "verified",
        "published_status": "published",
        "published_at": datetime(2025, 2, 1, 0, 0, 0, tzinfo=timezone.utc),
        "timelines": [
            {"date": date(2024, 12, 1), "title": "BI dan OJK umumkan reformasi biaya", "description": "Pakat reformasi biaya perbankan diumumkan."},
            {"date": date(2025, 2, 1), "title": "Implementasi bertahap", "description": "Bank mulai menerapkan biaya admin baru dan transfer gratis."},
        ],
        "sources": [
            {"source_type": "official", "title": "Pakar Reformasi Biaya Perbankan BI-OJK", "url": "https://www.bi.go.id/", "snippet": "Pengumuman resmi reformasi biaya perbankan.", "site_name": "Bank Indonesia", "published_date": date(2024, 12, 1), "verification_status": "verified"},
        ],
    },
    {
        "title": "Undang-Undang Perlindungan Pekerja Gig Economy",
        "status": "wacana",
        "slug": "uu-perlindungan-pekerja-gig-economy",
        "category_slug": "tenaga-kerja",
        "summary_30sec": "DPR membahas RUU Perlindungan Pekerja Gig Economy (ojol, kurir, freelancer digital). RUU ini mengatur jam kerja, asuransi, dan status kerja bagi pekerja platform.",
        "summary_long": "RUU Perlindungan Pekerja Gig Economy diajukan untuk mengatur hak-hak pekerja platform seperti pengemudi ojek online, kurir pengantaran, dan freelancer digital. RUU mengatur jam kerja minimum, asuransi kecelakaan kerja, jaminan penghasilan minimum, dan status kerja yang jelas. Masih dalam tahap pembahasan awal di DPR.",
        "simple_explanation": "Apa yang mau diatur? Ada undang-undang baru yang mau lindungi pekerja gig (ojol, kurir, freelancer). Aturannya: jam kerja jelas, ada asuransi, dan penghasilan minimum. Kenapa butuh? Karena pekerja gig sekarang nggak punya status kerja yang jelas. Mereka dianggap mitra, bukan karyawan. Jadi nggak dapet hak-hak kayak orang kerja biasa.",
        "impact_explanation": "Siapa yang terdampak: Pekerja gig (ojol, kurir, freelancer), platform digital\nApa yang berubah: Pengaturan jam kerja, asuransi, status kerja\nKapan berlaku: Masih wacana, dalam pembahasan DPR",
        "affected_groups": "Pekerja gig, platform digital",
        "government_claim": "RUU ini memberikan kepastian hukum dan perlindungan bagi pekerja gig.",
        "public_criticism": "Platform menilai regulasi bisa meningkatkan biaya operasional dan mengurangi fleksibilitas.",
        "source_confidence": "low",
        "verification_status": "needs_verification",
        "published_status": "draft",
    },
]


def seed_policies():
    import re as re_module

    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        admin = db.query(User).filter(User.email == "admin@kawalkebijakan.id").first()
        if not admin:
            admin = User(
                email="admin@kawalkebijakan.id",
                hashed_password=get_password_hash("admin123"),
                full_name="Admin KawalKebijakan",
                role="admin",
                is_active=True,
            )
            db.add(admin)
            db.commit()
            db.refresh(admin)

        for policy_data in POLICIES_DATA:
            existing = db.query(Policy).filter(Policy.slug == policy_data["slug"]).first()
            if existing:
                print(f"  Skip (exists): {policy_data['title']}")
                continue

            category = db.query(Category).filter(Category.slug == policy_data["category_slug"]).first()
            if not category:
                print(f"  Skip (no category): {policy_data['category_slug']}")
                continue

            timelines_data = policy_data.pop("timelines", [])
            sources_data = policy_data.pop("sources", [])
            category_slug = policy_data.pop("category_slug")

            policy = Policy(
                **policy_data,
                primary_category_id=category.id,
                created_by=admin.id,
            )
            db.add(policy)
            db.flush()

            db.add(PolicyCategory(policy_id=policy.id, category_id=category.id))

            for t_data in timelines_data:
                db.add(PolicyTimeline(policy_id=policy.id, **t_data))

            for s_data in sources_data:
                db.add(Source(policy_id=policy.id, **s_data))

            status_label = policy_data.get("published_status", "draft")
            print(f"  Created ({status_label}): {policy_data['title']}")

        db.commit()
        print(f"\nDone! Seeded {len(POLICIES_DATA)} policies.")

    finally:
        db.close()


if __name__ == "__main__":
    seed_policies()